title: Hina Jajoo
description: Senior Engineer with 12+ years of experience building scalable Backend and AI Infrastructure
logo: assets/profile.jpeg
author: Hina Jajoo
email: jajoo.hina03@gmail.com


# Remote theme for GitHub Pages
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme


# Social links
linkedin_username: hinajajoo

# Navigation
show_downloads: false

# Google Analytics (optional - uncomment and add your tracking ID if needed)
# google_analytics: G-XXXXXXXXXX

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections
collections_dir: collections 