title: Hina Jajoo
description: Senior Engineer with 12+ years of experience building scalable Backend and AI Infrastructure
author: Hina Jajoo
email: jajoo.hina03@gmail.com


# Remote theme for GitHub Pages
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme


# Social links
linkedin_username: hinajajoo

# Navigation
show_downloads: false

# Google Analytics
google_analytics: G-Q4L92T8GH8

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections
collections_dir: collections 